<a href="https://www.kaggle.com/code/sadikemir/work-rate-predict?scriptVersionId=229204127" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.linear_model import LinearRegression

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/student-marks-dataset/Student_Marks.csv


In [2]:
df=pd.read_csv('/kaggle/input/student-marks-dataset/Student_Marks.csv')

In [3]:
df.columns=['sinif','saat','puan']
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [4]:
y= df[['puan']]
x= df[['sinif','saat']]

In [5]:
l= LinearRegression()
model=l.fit(x,y)

In [6]:
model.predict([[3,2]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[8.93416357]])

In [7]:
model.coef_ #katsayı

array([[1.86405074, 5.39917879]])

In [8]:
model.intercept_ #sabit


array([-7.45634623])

In [9]:
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [10]:
s1=model.predict([[3,4.508]])[0][0]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [11]:
-(19.202-s1)/19.202

0.17046682485899461

In [12]:
model.score(x,y)

0.9403656320238896